### ISSUE TITLE
signif has wrong type hint

### ISSUE THREAD

**Issue by salabim** [nyggus/rounder#34]
The type hint for x in signif is IntOrFloat, where that should be Number.
Also, the return type is also Number.

**Comment by nyggus** [comment]
Currently, we have `x: float` (not `IntOrFloat`), but it's a minor detail. The problem is that the current version is correct given the implementation. I mean, it's not enough to change the type hint, as it's correct. We need to change the implementation.

Look:
```python
>>> import rounder
>>> from decimal import Decimal
>>> rounder.signif(Decimal("1.234567"), 3)
Traceback (most recent call last):
    ...
TypeError: unsupported operand type(s) for *: 'decimal.Decimal' and 'float'
>>> from fractions import Fraction
>>> round(Fraction(1, 3), 3)
Fraction(333, 1000)
>>> rounder.round_object(Fraction(1, 3), 3)
Fraction(333, 1000)
>>> rounder.signif(Fraction(1, 3), 3)
Fraction(5998794703657501, 18014398509481984)
```
So, clearly `signif` does not work fine for `fractions.Fraction` and `decimal.Decimal`, so we need to change its implementation in order to change its type hint to `numbers.Number`.

**Comment by salabim** [comment]
I would say: Just check for float and forget about Decimal and Fraction.

**Comment by nyggus** [comment]
Sounds fine for the moment. But in the long run, it does sound strange to keep `signify`'s API different from that of `rounder`'s. So, in a free moment, I will try to have a look at this. Since I have plenty of things to do with other stuff, and this seems like of a minor priority, this can mean far later than sooner. But I will keep this issue open.

**Comment by salabim** [comment]
I couldn't resist implementing this. The change is actually surprisingly simple!

Please find the new implementation (with some corrections to the doctests) and the update test file attached as a zip file (for me more straightforward than creating a pull request, now).
[rounder.zip](https://github.com/nyggus/rounder/files/11589760/rounder.zip)

**Comment by nyggus** [comment]
Great, thanks. I will look at this, as static checkers throw a number of errors. Also, the return type of `signif` needs to be changed.  Let me work on this.

**Comment by salabim** [comment]
This is one of those examples that type hints are more a nuisance than that is adds anything!

**Comment by nyggus** [comment]
Definitely!
